In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
training_data=pd.read_csv(r"C:\Users\ojoja\Desktop\works\DSML project 1\train_data.csv", header=None)
training_data.head(5)

,0,1,2,3,4,5,6,7,8,9,...,553,554,555,556,557,558,559,560,561,562
0,NaN,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,...,fBodyBodyGyroJerkMag-skewness(),fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject
1,356.0,0.28643265,-0.023842891,-0.12273754,-0.91558377,-0.71079378,-0.88022592,-0.93242863,-0.72031385,-0.8816573,...,-0.35777204,-0.75258188,-0.21750239999999998,0.22982607,0.15479147,-0.43113428,-0.761361,0.25057955,-0.046895310999999995,3
2,4482.0,0.33325764,-0.0013074393,-0.16658065,-0.034498107,-0.062471418,-0.28326757,-0.059697907,-0.17491186,-0.33866078,...,0.30832381,0.048713095,-0.19136029,-0.58031567,-0.42381023,0.68959733,-0.76546931,0.23737144,-0.06777138099999999,22
3,10012.0,0.26679666,-0.018683215,-0.10114222,-0.9908738000000001,-0.98900112,-0.98725473,-0.99165911,-0.98785924,-0.98542987,...,-0.38844176,-0.7035769000000001,-0.15260086,0.16209136,-0.62805232,0.55179469,0.58776753,-0.53650829,-0.46919277,24
4,4386.0,0.27636266,-0.020289165,-0.11370088,-0.99573283,-0.93909382,-0.98441757,-0.99701297,-0.93617989,-0.98372783,...,0.054211777999999995,-0.43075346,0.029985649,-0.094248447,0.025219245,-0.4080699,-0.81922672,0.21379382,-0.031300688,22

In [3]:
training_data = training_data.drop(labels=0, axis=0)
training_data

,0,1,2,3,4,5,6,7,8,9,...,553,554,555,556,557,558,559,560,561,562
1,356.0,0.28643265,-0.023842891,-0.12273754,-0.91558377,-0.71079378,-0.88022592,-0.93242863,-0.72031385,-0.8816573,...,-0.35777204,-0.75258188,-0.21750239999999998,0.22982607,0.15479147,-0.43113428,-0.761361,0.25057955,-0.046895310999999995,3
2,4482.0,0.33325764,-0.0013074393,-0.16658065,-0.034498107,-0.062471418,-0.28326757,-0.059697907,-0.17491186,-0.33866078,...,0.30832381,0.048713095,-0.19136029,-0.58031567,-0.42381023,0.68959733,-0.76546931,0.23737144,-0.06777138099999999,22
3,10012.0,0.26679666,-0.018683215,-0.10114222,-0.9908738000000001,-0.98900112,-0.98725473,-0.99165911,-0.98785924,-0.98542987,...,-0.38844176,-0.7035769000000001,-0.15260086,0.16209136,-0.62805232,0.55179469,0.58776753,-0.53650829,-0.46919277,24
4,4386.0,0.27636266,-0.020289165,-0.11370088,-0.99573283,-0.93909382,-0.98441757,-0.99701297,-0.93617989,-0.98372783,...,0.054211777999999995,-0.43075346,0.029985649,-0.094248447,0.025219245,-0.4080699,-0.81922672,0.21379382,-0.031300688,22
5,3751.0,0.26823055,-0.0041461452000000005,-0.094502785,0.47312327,0.45240296,-0.15260038,0.450082,0.48276443,-0.23938305,...,-0.13963925,-0.55854963,0.27837241,0.36323953,0.88543165,0.84841376,-0.7797605,0.24938377,0.03548351,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8235,8324.0,0.270511,-0.011321,-0.111377,-0.988057,-0.961229,-0.951407,-0.989752,-0.958753,-0.96505,...,-0.250141,-0.615815,-0.35349,-0.081501,0.181517,-0.180534,0.65869,-0.091334,0.961636,10
8236,10206.0,0.260897,-0.017322,-0.103011,-0.988656,-0.990926,-0.989076,-0.989816,-0.990775,-0.988472,...,-0.255976,-0.667159,-0.079052,-0.107393,-0.547206,0.564335,0.435081,-0.503752,-0.485656,24
8237,6253.0,0.278648,-0.020038,-0.11859,-0.983932,-0.912261,-0.955945,-0.98713,-0.917041,-0.957747,...,0.354233,0.146016,-0.068825,-0.060211,-0.727493,-0.655778,-0.795575,0.238281,-0.000787,28
8238,10123.0,0.283642,-0.006992,-0.129778,-0.994152,-0.954562,-0.951844,-0.995321,-0.955989,-0.944934,...,-0.586855,-0.881097,-0.051389,-0.015944,-0.759481,-0.805523,-0.86431,0.188362,0.044799,24
8239,5600.0,0.216534,-0.020933,-0.134184,-0.319141,-0.062512,-0.31639,-0.358099,-0.011323,-0.317022,...,0.060853,-0.351961,0.666435,0.068822,-0.53956,-0.568153,-0.851314,0.16928,-0.059874,26

In [4]:
training_data.isnull().values.any()

False

In [5]:
training_data = training_data.astype(float)
training_data.head(5)

,0,1,2,3,4,5,6,7,8,9,...,553,554,555,556,557,558,559,560,561,562
1,356.0,0.286433,-0.023843,-0.122738,-0.915584,-0.710794,-0.880226,-0.932429,-0.720314,-0.881657,...,-0.357772,-0.752582,-0.217502,0.229826,0.154791,-0.431134,-0.761361,0.250580,-0.046895,3.0
2,4482.0,0.333258,-0.001307,-0.166581,-0.034498,-0.062471,-0.283268,-0.059698,-0.174912,-0.338661,...,0.308324,0.048713,-0.191360,-0.580316,-0.423810,0.689597,-0.765469,0.237371,-0.067771,22.0
3,10012.0,0.266797,-0.018683,-0.101142,-0.990874,-0.989001,-0.987255,-0.991659,-0.987859,-0.985430,...,-0.388442,-0.703577,-0.152601,0.162091,-0.628052,0.551795,0.587768,-0.536508,-0.469193,24.0
4,4386.0,0.276363,-0.020289,-0.113701,-0.995733,-0.939094,-0.984418,-0.997013,-0.936180,-0.983728,...,0.054212,-0.430753,0.029986,-0.094248,0.025219,-0.408070,-0.819227,0.213794,-0.031301,22.0
5,3751.0,0.268231,-0.004146,-0.094503,0.473123,0.452403,-0.152600,0.450082,0.482764,-0.239383,...,-0.139639,-0.558550,0.278372,0.363240,0.885432,0.848414,-0.779760,0.249384,0.035484,19.0

In [6]:
training_data_classes=pd.read_csv(r"C:\Users\ojoja\Desktop\works\DSML project 1\train_labels.csv", header=None)
training_data_classes.head(5)

         0         1
0      NaN  Activity
1    356.0  STANDING
2   4482.0   WALKING
3  10012.0    LAYING
4   4386.0  STANDING

In [7]:
training_data_classes = training_data_classes.drop(labels=0, axis=0)
training_data_classes.head(5)

         0                   1
1    356.0            STANDING
2   4482.0             WALKING
3  10012.0              LAYING
4   4386.0            STANDING
5   3751.0  WALKING_DOWNSTAIRS

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
x = training_data.iloc[:,0:]
y = training_data_classes.iloc[:,1:].values.ravel()
# split the dataset
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

## Naive Bayes

In [11]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report

nb = GaussianNB().fit(np.array(X_train), y_train)
pred_train = nb.predict(np.array(X_test))
print(classification_report(y_test, pred_train))

                    precision    recall  f1-score   support

            LAYING       0.98      0.99      0.99       429
           SITTING       0.90      0.66      0.76       445
          STANDING       0.75      0.93      0.83       451
           WALKING       0.90      0.71      0.79       424
WALKING_DOWNSTAIRS       0.81      0.76      0.78       339
  WALKING_UPSTAIRS       0.70      0.92      0.80       384

          accuracy                           0.83      2472
         macro avg       0.84      0.83      0.83      2472
      weighted avg       0.84      0.83      0.83      2472

In [12]:
nb_tune = GridSearchCV(nb, param_grid={'var_smoothing': [0.00000001, 0.000000001, 0.00000001]},cv=5, scoring='accuracy').fit(np.array(x), y)
pred_train = nb_tune.predict(np.array(x))
print(classification_report(y, pred_train))

                    precision    recall  f1-score   support

            LAYING       0.99      0.99      0.99      1525
           SITTING       0.94      0.63      0.75      1440
          STANDING       0.74      0.96      0.83      1514
           WALKING       0.88      0.73      0.80      1382
WALKING_DOWNSTAIRS       0.81      0.72      0.76      1137
  WALKING_UPSTAIRS       0.71      0.92      0.80      1241

          accuracy                           0.83      8239
         macro avg       0.84      0.83      0.82      8239
      weighted avg       0.85      0.83      0.83      8239

## Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression().fit(np.array(X_train), y_train)
pred_train = lr.predict(np.array(X_test))
print(classification_report(y_test, pred_train))

                    precision    recall  f1-score   support

            LAYING       0.97      1.00      0.98       429
           SITTING       0.83      0.69      0.76       445
          STANDING       0.75      0.86      0.80       451
           WALKING       0.76      0.76      0.76       424
WALKING_DOWNSTAIRS       0.70      0.57      0.63       339
  WALKING_UPSTAIRS       0.76      0.87      0.81       384

          accuracy                           0.80      2472
         macro avg       0.79      0.79      0.79      2472
      weighted avg       0.80      0.80      0.80      2472

In [14]:
# # importing cross-validation from sklearn package.
# from sklearn.model_selection import cross_val_score,KFold
  
# kf=KFold(n_splits=5)
# score=cross_val_score(lr,x,y,cv=kf)
# print("Cross Validation Scores are {}".format(score))
# print("Average Cross Validation score :{}".format(score.mean()))

In [26]:
lr_tune = GridSearchCV(lr, param_grid={'C': [0.01,0.1,1]},cv=5, scoring='accuracy').fit(np.array(x), y)
pred_train = lr_tune.predict(np.array(x))
print(classification_report(y, pred_train))

                    precision    recall  f1-score   support

            LAYING       0.95      1.00      0.97      1525
           SITTING       0.78      0.71      0.74      1440
          STANDING       0.79      0.81      0.80      1514
           WALKING       0.74      0.77      0.76      1382
WALKING_DOWNSTAIRS       0.73      0.58      0.65      1137
  WALKING_UPSTAIRS       0.75      0.87      0.80      1241

          accuracy                           0.80      8239
         macro avg       0.79      0.79      0.79      8239
      weighted avg       0.79      0.80      0.79      8239

## K-Nearest Neighbor

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier().fit(np.array(X_train), y_train)
pred_train = knn.predict(np.array(X_test))
print(classification_report(y_test, pred_train))

                    precision    recall  f1-score   support

            LAYING       0.99      0.99      0.99       429
           SITTING       0.98      0.96      0.97       445
          STANDING       0.97      0.98      0.97       451
           WALKING       0.99      0.99      0.99       424
WALKING_DOWNSTAIRS       0.95      0.93      0.94       339
  WALKING_UPSTAIRS       0.95      0.97      0.96       384

          accuracy                           0.97      2472
         macro avg       0.97      0.97      0.97      2472
      weighted avg       0.97      0.97      0.97      2472

In [17]:
# # importing cross-validation from sklearn package.
# from sklearn.model_selection import cross_val_score,KFold
  
# kf=KFold(n_splits=5)
# score=cross_val_score(knn,x,y,cv=kf)
# print("Cross Validation Scores are {}".format(score))
# print("Average Cross Validation score :{}".format(score.mean()))

In [27]:
knn_tune = GridSearchCV(knn, param_grid={'n_neighbors': [5,10,15], 'leaf_size': [5, 10],},cv=5, scoring='accuracy').fit(np.array(x), y)
pred_train = knn_tune.predict(np.array(x))
print(classification_report(y, pred_train))

                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00      1525
           SITTING       1.00      1.00      1.00      1440
          STANDING       1.00      1.00      1.00      1514
           WALKING       1.00      1.00      1.00      1382
WALKING_DOWNSTAIRS       1.00      0.99      1.00      1137
  WALKING_UPSTAIRS       1.00      1.00      1.00      1241

          accuracy                           1.00      8239
         macro avg       1.00      1.00      1.00      8239
      weighted avg       1.00      1.00      1.00      8239

## Random Forest

In [19]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 100) 
clf.fit(np.array(X_train), y_train) 
pred_train = clf.predict(np.array(X_test))
print(classification_report(y_test, pred_train))

                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       429
           SITTING       0.97      0.97      0.97       445
          STANDING       0.97      0.97      0.97       451
           WALKING       0.98      0.97      0.98       424
WALKING_DOWNSTAIRS       0.97      0.96      0.97       339
  WALKING_UPSTAIRS       0.96      0.99      0.98       384

          accuracy                           0.98      2472
         macro avg       0.98      0.98      0.98      2472
      weighted avg       0.98      0.98      0.98      2472

In [20]:
# importing cross-validation from sklearn package.
from sklearn.model_selection import cross_val_score,KFold
  
kf=KFold(n_splits=5)
score=cross_val_score(clf,x,y,cv=kf)
print("Cross Validation Scores are {}".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Cross Validation Scores are [0.96966019 0.97936893 0.97572816 0.98118932 0.9726776 ]
Average Cross Validation score :0.9757248395140324

In [70]:
clf_tune = GridSearchCV(clf, param_grid={'n_estimators': [5,100,500], 'max_leaf_nodes': [ 10, 'None']},cv=5, scoring='accuracy').fit(np.array(x), y)
pred_train = clf_tune.predict(np.array(x))
print(classification_report(y, pred_train))

                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00      1525
           SITTING       0.89      0.87      0.88      1440
          STANDING       0.88      0.90      0.89      1514
           WALKING       0.91      0.94      0.93      1382
WALKING_DOWNSTAIRS       0.92      0.84      0.88      1137
  WALKING_UPSTAIRS       0.87      0.92      0.90      1241

          accuracy                           0.91      8239
         macro avg       0.91      0.91      0.91      8239
      weighted avg       0.91      0.91      0.91      8239

## Testing

In [22]:
df_test = pd.read_csv(r"C:\Users\ojoja\Desktop\works\DSML project 1\test_data.csv", header=None)
df_test.head(5)

,0,1,2,3,4,5,6,7,8,9,...,553,554,555,556,557,558,559,560,561,562
0,NaN,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,...,fBodyBodyGyroJerkMag-skewness(),fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject
1,6597.0,0.23833689,-0.039949828,-0.15825651,0.28361522,0.22657526,-0.13321591,0.24460721,0.21395016,-0.16897136,...,-0.18987788,-0.58513606,0.095017028,-0.68362295,0.93686967,-0.63585207,-0.74947207,0.23548369,0.12657354,28
2,7609.0,0.12592012,-0.027658255,-0.050069385999999994,0.082014241,0.10996979,-0.19943931,-0.019577853,0.0064695215,-0.20772707,...,-0.20434365,-0.64808817,0.48892673,-0.44076514,0.13856943,-0.12379136,-0.67013211,0.30375356,-0.081748192,2
3,10110.0,0.28163039,-0.012995335,-0.082663678,-0.99358439,-0.92441377,-0.9166434999999999,-0.99489717,-0.91970198,-0.9107417999999999,...,-0.38579952,-0.75100579,-0.0050780925,0.076865023,-0.094954446,0.6618236999999999,-0.84758178,0.19945019,0.048085757,24
4,1924.0,0.27654044,-0.014060261999999999,-0.10158827,-0.99628861,-0.97168449,-0.98567532,-0.99689252,-0.96950893,-0.98752236,...,-0.25669038,-0.71667909,0.02991482,0.13245643,0.59969561,0.74040625,-0.79567371,0.19317578,-0.090911249,11

In [23]:
df_test = df_test.drop(labels=0, axis=0)
df_test.head(5)

,0,1,2,3,4,5,6,7,8,9,...,553,554,555,556,557,558,559,560,561,562
1,6597.0,0.23833689,-0.039949828,-0.15825651,0.28361522,0.22657526,-0.13321591,0.24460721,0.21395016,-0.16897136,...,-0.18987788,-0.58513606,0.095017028,-0.68362295,0.93686967,-0.63585207,-0.74947207,0.23548369,0.12657354,28
2,7609.0,0.12592012,-0.027658255,-0.050069385999999994,0.082014241,0.10996979,-0.19943931,-0.019577853,0.0064695215,-0.20772707,...,-0.20434365,-0.64808817,0.48892673,-0.44076514,0.13856943,-0.12379136,-0.67013211,0.30375356,-0.081748192,2
3,10110.0,0.28163039,-0.012995335,-0.082663678,-0.99358439,-0.92441377,-0.9166434999999999,-0.99489717,-0.91970198,-0.9107417999999999,...,-0.38579952,-0.75100579,-0.0050780925,0.076865023,-0.094954446,0.6618236999999999,-0.84758178,0.19945019,0.048085757,24
4,1924.0,0.27654044,-0.014060261999999999,-0.10158827,-0.99628861,-0.97168449,-0.98567532,-0.99689252,-0.96950893,-0.98752236,...,-0.25669038,-0.71667909,0.02991482,0.13245643,0.59969561,0.74040625,-0.79567371,0.19317578,-0.090911249,11
5,5088.0,0.28601661,-0.017170400000000002,-0.12296015,-0.9970193000000002,-0.97262061,-0.99416342,-0.99744425,-0.97459401,-0.99393255,...,-0.62898145,-0.85496504,0.0061379527,-0.11033156,0.24495496,0.22709497,-0.63678904,0.17084978,-0.23222126,25

In [24]:
df_test = df_test.astype(float)
df_test.head(5)

,0,1,2,3,4,5,6,7,8,9,...,553,554,555,556,557,558,559,560,561,562
1,6597.0,0.238337,-0.039950,-0.158257,0.283615,0.226575,-0.133216,0.244607,0.213950,-0.168971,...,-0.189878,-0.585136,0.095017,-0.683623,0.936870,-0.635852,-0.749472,0.235484,0.126574,28.0
2,7609.0,0.125920,-0.027658,-0.050069,0.082014,0.109970,-0.199439,-0.019578,0.006470,-0.207727,...,-0.204344,-0.648088,0.488927,-0.440765,0.138569,-0.123791,-0.670132,0.303754,-0.081748,2.0
3,10110.0,0.281630,-0.012995,-0.082664,-0.993584,-0.924414,-0.916643,-0.994897,-0.919702,-0.910742,...,-0.385800,-0.751006,-0.005078,0.076865,-0.094954,0.661824,-0.847582,0.199450,0.048086,24.0
4,1924.0,0.276540,-0.014060,-0.101588,-0.996289,-0.971684,-0.985675,-0.996893,-0.969509,-0.987522,...,-0.256690,-0.716679,0.029915,0.132456,0.599696,0.740406,-0.795674,0.193176,-0.090911,11.0
5,5088.0,0.286017,-0.017170,-0.122960,-0.997019,-0.972621,-0.994163,-0.997444,-0.974594,-0.993933,...,-0.628981,-0.854965,0.006138,-0.110332,0.244955,0.227095,-0.636789,0.170850,-0.232221,25.0

In [25]:
test_classes = pd.DataFrame(clf.predict(df_test))
test_classes

                       0
0     WALKING_DOWNSTAIRS
1     WALKING_DOWNSTAIRS
2               STANDING
3               STANDING
4               STANDING
...                  ...
2055             WALKING
2056              LAYING
2057              LAYING
2058             WALKING
2059             WALKING

[2060 rows x 1 columns]